
default: &default
  adapter: postgresql
  encoding: unicode
  username: rails
  password: Rails1234?

development:
  <<: *default
  database: elittest_development

test:
  <<: *default
  database: elittest_test

production:
  <<: *default
  database: elittest_production
